# We need 2 secrets, 1 for the database in the database namespace,
  # the second one is used by keycloak to connect to the database.
  # The keycloak secret is needed in the identity namespace that is
  # why we need 2 secrets defined.
---
apiVersion: v1
kind: Secret
metadata:
  name: retool-db-config
  namespace: retool
type: kubernetes.io/basic-auth
data:
  password: {{ .Values.retool.config.postgresql.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retool.cluster-db-secret" . }}
  namespace: database
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.retool.config.postgresql.user | b64enc }}
  password: {{ .Values.retool.config.postgresql.password }}
