# We need 2 secrets, 1 for the database in the database namespace,
# the second one is used by keycloak to connect to the database.
# The keycloak secret is needed in the identity namespace that is
# why we need 2 secrets defined.
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-config
  namespace: identity
type: kubernetes.io/basic-auth
data:
  host: {{ .Values.database.host | b64enc }}
  port: {{ .Values.database.port | toString | b64enc }}
  database: {{ .Values.database.name | b64enc }}
  user: {{ .Values.database.user }}
  password: {{ .Values.database.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.cluster-db-secret" . }}
  namespace: database
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.database.user }}
  password: {{ .Values.database.password }}
