apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sre-tech-challenge-senior.pvcName" . }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  selector:
    matchLabels:
      app: {{ include "sre-tech-challenge-senior.name" . }}
