apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sre-tech-challenge-senior.secretName" . }}
  labels:
    app: {{ include "sre-tech-challenge-senior.name" . }}
type: Opaque
data:
  my-secret: {{ .Values.secret }}
