apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-tech-challenge-senior.serviceName" . }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ include "sre-tech-challenge-senior.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.containerPort }}
    targetPort: {{ .Values.targetPort }}
